#
# .eslintrc.yml
#

root: true
parserOptions:
  sourceType: module
  ecmaVersion: 2018
env:
  node: true
  jest: true
rules:
  no-unused-vars: [off]
extends:
  - standard
  - prettier
  - prettier/standard
